<?xml version="1.0" encoding="utf-8"?><Database Name="Hotel_Info" Class="MyHotelDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Hotel_Info.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Hotel_Management.Properties.Settings" SettingsPropertyName="Hotel_InfoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Admin_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Admin_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Admin_password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Receptionist" Member="Receptionists">
    <Type Name="Receptionist">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rec_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rec_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rec_phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rec_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rec_password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="Room_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Room_num" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Room_type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Room_floor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Room_price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Room_bookingStatus" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Guest" Member="Guests">
    <Type Name="Guest">
      <Column Name="Guest_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Guest_firstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_lastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Guest_gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_nationality" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_national_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Guest_roomType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_roomFloor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_roomNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Guest_checkIn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Guest_checkOut" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Guest_stayingDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Guest_confirmationStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Guest_payingStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Guest_confirmByReceptionist" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>