#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hotel_Info")]
	public partial class MyHotelDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertReceptionist(Receptionist instance);
    partial void UpdateReceptionist(Receptionist instance);
    partial void DeleteReceptionist(Receptionist instance);
    partial void InsertRoom(Room instance);
    partial void UpdateRoom(Room instance);
    partial void DeleteRoom(Room instance);
    partial void InsertGuest(Guest instance);
    partial void UpdateGuest(Guest instance);
    partial void DeleteGuest(Guest instance);
    #endregion
		
		public MyHotelDBDataContext() : 
				base(global::Hotel_Management.Properties.Settings.Default.Hotel_InfoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyHotelDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyHotelDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyHotelDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyHotelDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Receptionist> Receptionists
		{
			get
			{
				return this.GetTable<Receptionist>();
			}
		}
		
		public System.Data.Linq.Table<Room> Rooms
		{
			get
			{
				return this.GetTable<Room>();
			}
		}
		
		public System.Data.Linq.Table<Guest> Guests
		{
			get
			{
				return this.GetTable<Guest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Admin_id;
		
		private string _Admin_name;
		
		private string _Admin_password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdmin_idChanging(int value);
    partial void OnAdmin_idChanged();
    partial void OnAdmin_nameChanging(string value);
    partial void OnAdmin_nameChanged();
    partial void OnAdmin_passwordChanging(string value);
    partial void OnAdmin_passwordChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Admin_id
		{
			get
			{
				return this._Admin_id;
			}
			set
			{
				if ((this._Admin_id != value))
				{
					this.OnAdmin_idChanging(value);
					this.SendPropertyChanging();
					this._Admin_id = value;
					this.SendPropertyChanged("Admin_id");
					this.OnAdmin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_name
		{
			get
			{
				return this._Admin_name;
			}
			set
			{
				if ((this._Admin_name != value))
				{
					this.OnAdmin_nameChanging(value);
					this.SendPropertyChanging();
					this._Admin_name = value;
					this.SendPropertyChanged("Admin_name");
					this.OnAdmin_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_password
		{
			get
			{
				return this._Admin_password;
			}
			set
			{
				if ((this._Admin_password != value))
				{
					this.OnAdmin_passwordChanging(value);
					this.SendPropertyChanging();
					this._Admin_password = value;
					this.SendPropertyChanged("Admin_password");
					this.OnAdmin_passwordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Receptionist")]
	public partial class Receptionist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Rec_id;
		
		private string _Rec_name;
		
		private string _Rec_phone;
		
		private string _Rec_email;
		
		private string _Rec_password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRec_idChanging(int value);
    partial void OnRec_idChanged();
    partial void OnRec_nameChanging(string value);
    partial void OnRec_nameChanged();
    partial void OnRec_phoneChanging(string value);
    partial void OnRec_phoneChanged();
    partial void OnRec_emailChanging(string value);
    partial void OnRec_emailChanged();
    partial void OnRec_passwordChanging(string value);
    partial void OnRec_passwordChanged();
    #endregion
		
		public Receptionist()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rec_id", DbType="Int NOT NULL")]
		public int Rec_id
		{
			get
			{
				return this._Rec_id;
			}
			set
			{
				if ((this._Rec_id != value))
				{
					this.OnRec_idChanging(value);
					this.SendPropertyChanging();
					this._Rec_id = value;
					this.SendPropertyChanged("Rec_id");
					this.OnRec_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rec_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rec_name
		{
			get
			{
				return this._Rec_name;
			}
			set
			{
				if ((this._Rec_name != value))
				{
					this.OnRec_nameChanging(value);
					this.SendPropertyChanging();
					this._Rec_name = value;
					this.SendPropertyChanged("Rec_name");
					this.OnRec_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rec_phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rec_phone
		{
			get
			{
				return this._Rec_phone;
			}
			set
			{
				if ((this._Rec_phone != value))
				{
					this.OnRec_phoneChanging(value);
					this.SendPropertyChanging();
					this._Rec_phone = value;
					this.SendPropertyChanged("Rec_phone");
					this.OnRec_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rec_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rec_email
		{
			get
			{
				return this._Rec_email;
			}
			set
			{
				if ((this._Rec_email != value))
				{
					this.OnRec_emailChanging(value);
					this.SendPropertyChanging();
					this._Rec_email = value;
					this.SendPropertyChanged("Rec_email");
					this.OnRec_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rec_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Rec_password
		{
			get
			{
				return this._Rec_password;
			}
			set
			{
				if ((this._Rec_password != value))
				{
					this.OnRec_passwordChanging(value);
					this.SendPropertyChanging();
					this._Rec_password = value;
					this.SendPropertyChanged("Rec_password");
					this.OnRec_passwordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Room")]
	public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Room_id;
		
		private string _Room_num;
		
		private string _Room_type;
		
		private string _Room_floor;
		
		private int _Room_price;
		
		private string _Room_bookingStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoom_idChanging(int value);
    partial void OnRoom_idChanged();
    partial void OnRoom_numChanging(string value);
    partial void OnRoom_numChanged();
    partial void OnRoom_typeChanging(string value);
    partial void OnRoom_typeChanged();
    partial void OnRoom_floorChanging(string value);
    partial void OnRoom_floorChanged();
    partial void OnRoom_priceChanging(int value);
    partial void OnRoom_priceChanged();
    partial void OnRoom_bookingStatusChanging(string value);
    partial void OnRoom_bookingStatusChanged();
    #endregion
		
		public Room()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Room_id
		{
			get
			{
				return this._Room_id;
			}
			set
			{
				if ((this._Room_id != value))
				{
					this.OnRoom_idChanging(value);
					this.SendPropertyChanging();
					this._Room_id = value;
					this.SendPropertyChanged("Room_id");
					this.OnRoom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_num", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Room_num
		{
			get
			{
				return this._Room_num;
			}
			set
			{
				if ((this._Room_num != value))
				{
					this.OnRoom_numChanging(value);
					this.SendPropertyChanging();
					this._Room_num = value;
					this.SendPropertyChanged("Room_num");
					this.OnRoom_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Room_type
		{
			get
			{
				return this._Room_type;
			}
			set
			{
				if ((this._Room_type != value))
				{
					this.OnRoom_typeChanging(value);
					this.SendPropertyChanging();
					this._Room_type = value;
					this.SendPropertyChanged("Room_type");
					this.OnRoom_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_floor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Room_floor
		{
			get
			{
				return this._Room_floor;
			}
			set
			{
				if ((this._Room_floor != value))
				{
					this.OnRoom_floorChanging(value);
					this.SendPropertyChanging();
					this._Room_floor = value;
					this.SendPropertyChanged("Room_floor");
					this.OnRoom_floorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_price", DbType="Int NOT NULL")]
		public int Room_price
		{
			get
			{
				return this._Room_price;
			}
			set
			{
				if ((this._Room_price != value))
				{
					this.OnRoom_priceChanging(value);
					this.SendPropertyChanging();
					this._Room_price = value;
					this.SendPropertyChanged("Room_price");
					this.OnRoom_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_bookingStatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Room_bookingStatus
		{
			get
			{
				return this._Room_bookingStatus;
			}
			set
			{
				if ((this._Room_bookingStatus != value))
				{
					this.OnRoom_bookingStatusChanging(value);
					this.SendPropertyChanging();
					this._Room_bookingStatus = value;
					this.SendPropertyChanged("Room_bookingStatus");
					this.OnRoom_bookingStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Guest")]
	public partial class Guest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Guest_id;
		
		private string _Guest_firstName;
		
		private string _Guest_lastName;
		
		private System.Nullable<System.DateTime> _Guest_birthday;
		
		private string _Guest_gender;
		
		private string _Guest_phone;
		
		private string _Guest_email;
		
		private string _Guest_address;
		
		private string _Guest_nationality;
		
		private string _Guest_national_id;
		
		private int _Guest_quantity;
		
		private string _Guest_roomType;
		
		private string _Guest_roomFloor;
		
		private string _Guest_roomNo;
		
		private System.Nullable<System.DateTime> _Guest_checkIn;
		
		private System.Nullable<System.DateTime> _Guest_checkOut;
		
		private int _Guest_stayingDay;
		
		private string _Guest_confirmationStatus;
		
		private string _Guest_payingStatus;
		
		private string _Guest_confirmByReceptionist;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGuest_idChanging(int value);
    partial void OnGuest_idChanged();
    partial void OnGuest_firstNameChanging(string value);
    partial void OnGuest_firstNameChanged();
    partial void OnGuest_lastNameChanging(string value);
    partial void OnGuest_lastNameChanged();
    partial void OnGuest_birthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnGuest_birthdayChanged();
    partial void OnGuest_genderChanging(string value);
    partial void OnGuest_genderChanged();
    partial void OnGuest_phoneChanging(string value);
    partial void OnGuest_phoneChanged();
    partial void OnGuest_emailChanging(string value);
    partial void OnGuest_emailChanged();
    partial void OnGuest_addressChanging(string value);
    partial void OnGuest_addressChanged();
    partial void OnGuest_nationalityChanging(string value);
    partial void OnGuest_nationalityChanged();
    partial void OnGuest_national_idChanging(string value);
    partial void OnGuest_national_idChanged();
    partial void OnGuest_quantityChanging(int value);
    partial void OnGuest_quantityChanged();
    partial void OnGuest_roomTypeChanging(string value);
    partial void OnGuest_roomTypeChanged();
    partial void OnGuest_roomFloorChanging(string value);
    partial void OnGuest_roomFloorChanged();
    partial void OnGuest_roomNoChanging(string value);
    partial void OnGuest_roomNoChanged();
    partial void OnGuest_checkInChanging(System.Nullable<System.DateTime> value);
    partial void OnGuest_checkInChanged();
    partial void OnGuest_checkOutChanging(System.Nullable<System.DateTime> value);
    partial void OnGuest_checkOutChanged();
    partial void OnGuest_stayingDayChanging(int value);
    partial void OnGuest_stayingDayChanged();
    partial void OnGuest_confirmationStatusChanging(string value);
    partial void OnGuest_confirmationStatusChanged();
    partial void OnGuest_payingStatusChanging(string value);
    partial void OnGuest_payingStatusChanged();
    partial void OnGuest_confirmByReceptionistChanging(string value);
    partial void OnGuest_confirmByReceptionistChanged();
    #endregion
		
		public Guest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Guest_id
		{
			get
			{
				return this._Guest_id;
			}
			set
			{
				if ((this._Guest_id != value))
				{
					this.OnGuest_idChanging(value);
					this.SendPropertyChanging();
					this._Guest_id = value;
					this.SendPropertyChanged("Guest_id");
					this.OnGuest_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_firstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_firstName
		{
			get
			{
				return this._Guest_firstName;
			}
			set
			{
				if ((this._Guest_firstName != value))
				{
					this.OnGuest_firstNameChanging(value);
					this.SendPropertyChanging();
					this._Guest_firstName = value;
					this.SendPropertyChanged("Guest_firstName");
					this.OnGuest_firstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_lastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_lastName
		{
			get
			{
				return this._Guest_lastName;
			}
			set
			{
				if ((this._Guest_lastName != value))
				{
					this.OnGuest_lastNameChanging(value);
					this.SendPropertyChanging();
					this._Guest_lastName = value;
					this.SendPropertyChanged("Guest_lastName");
					this.OnGuest_lastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> Guest_birthday
		{
			get
			{
				return this._Guest_birthday;
			}
			set
			{
				if ((this._Guest_birthday != value))
				{
					this.OnGuest_birthdayChanging(value);
					this.SendPropertyChanging();
					this._Guest_birthday = value;
					this.SendPropertyChanged("Guest_birthday");
					this.OnGuest_birthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_gender", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_gender
		{
			get
			{
				return this._Guest_gender;
			}
			set
			{
				if ((this._Guest_gender != value))
				{
					this.OnGuest_genderChanging(value);
					this.SendPropertyChanging();
					this._Guest_gender = value;
					this.SendPropertyChanged("Guest_gender");
					this.OnGuest_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_phone
		{
			get
			{
				return this._Guest_phone;
			}
			set
			{
				if ((this._Guest_phone != value))
				{
					this.OnGuest_phoneChanging(value);
					this.SendPropertyChanging();
					this._Guest_phone = value;
					this.SendPropertyChanged("Guest_phone");
					this.OnGuest_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_email
		{
			get
			{
				return this._Guest_email;
			}
			set
			{
				if ((this._Guest_email != value))
				{
					this.OnGuest_emailChanging(value);
					this.SendPropertyChanging();
					this._Guest_email = value;
					this.SendPropertyChanged("Guest_email");
					this.OnGuest_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_address
		{
			get
			{
				return this._Guest_address;
			}
			set
			{
				if ((this._Guest_address != value))
				{
					this.OnGuest_addressChanging(value);
					this.SendPropertyChanging();
					this._Guest_address = value;
					this.SendPropertyChanged("Guest_address");
					this.OnGuest_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_nationality", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_nationality
		{
			get
			{
				return this._Guest_nationality;
			}
			set
			{
				if ((this._Guest_nationality != value))
				{
					this.OnGuest_nationalityChanging(value);
					this.SendPropertyChanging();
					this._Guest_nationality = value;
					this.SendPropertyChanged("Guest_nationality");
					this.OnGuest_nationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_national_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_national_id
		{
			get
			{
				return this._Guest_national_id;
			}
			set
			{
				if ((this._Guest_national_id != value))
				{
					this.OnGuest_national_idChanging(value);
					this.SendPropertyChanging();
					this._Guest_national_id = value;
					this.SendPropertyChanged("Guest_national_id");
					this.OnGuest_national_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_quantity", DbType="Int NOT NULL")]
		public int Guest_quantity
		{
			get
			{
				return this._Guest_quantity;
			}
			set
			{
				if ((this._Guest_quantity != value))
				{
					this.OnGuest_quantityChanging(value);
					this.SendPropertyChanging();
					this._Guest_quantity = value;
					this.SendPropertyChanged("Guest_quantity");
					this.OnGuest_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_roomType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_roomType
		{
			get
			{
				return this._Guest_roomType;
			}
			set
			{
				if ((this._Guest_roomType != value))
				{
					this.OnGuest_roomTypeChanging(value);
					this.SendPropertyChanging();
					this._Guest_roomType = value;
					this.SendPropertyChanged("Guest_roomType");
					this.OnGuest_roomTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_roomFloor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_roomFloor
		{
			get
			{
				return this._Guest_roomFloor;
			}
			set
			{
				if ((this._Guest_roomFloor != value))
				{
					this.OnGuest_roomFloorChanging(value);
					this.SendPropertyChanging();
					this._Guest_roomFloor = value;
					this.SendPropertyChanged("Guest_roomFloor");
					this.OnGuest_roomFloorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_roomNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guest_roomNo
		{
			get
			{
				return this._Guest_roomNo;
			}
			set
			{
				if ((this._Guest_roomNo != value))
				{
					this.OnGuest_roomNoChanging(value);
					this.SendPropertyChanging();
					this._Guest_roomNo = value;
					this.SendPropertyChanged("Guest_roomNo");
					this.OnGuest_roomNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_checkIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> Guest_checkIn
		{
			get
			{
				return this._Guest_checkIn;
			}
			set
			{
				if ((this._Guest_checkIn != value))
				{
					this.OnGuest_checkInChanging(value);
					this.SendPropertyChanging();
					this._Guest_checkIn = value;
					this.SendPropertyChanged("Guest_checkIn");
					this.OnGuest_checkInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_checkOut", DbType="DateTime")]
		public System.Nullable<System.DateTime> Guest_checkOut
		{
			get
			{
				return this._Guest_checkOut;
			}
			set
			{
				if ((this._Guest_checkOut != value))
				{
					this.OnGuest_checkOutChanging(value);
					this.SendPropertyChanging();
					this._Guest_checkOut = value;
					this.SendPropertyChanged("Guest_checkOut");
					this.OnGuest_checkOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_stayingDay", DbType="Int NOT NULL")]
		public int Guest_stayingDay
		{
			get
			{
				return this._Guest_stayingDay;
			}
			set
			{
				if ((this._Guest_stayingDay != value))
				{
					this.OnGuest_stayingDayChanging(value);
					this.SendPropertyChanging();
					this._Guest_stayingDay = value;
					this.SendPropertyChanged("Guest_stayingDay");
					this.OnGuest_stayingDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_confirmationStatus", DbType="VarChar(50)")]
		public string Guest_confirmationStatus
		{
			get
			{
				return this._Guest_confirmationStatus;
			}
			set
			{
				if ((this._Guest_confirmationStatus != value))
				{
					this.OnGuest_confirmationStatusChanging(value);
					this.SendPropertyChanging();
					this._Guest_confirmationStatus = value;
					this.SendPropertyChanged("Guest_confirmationStatus");
					this.OnGuest_confirmationStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_payingStatus", DbType="VarChar(50)")]
		public string Guest_payingStatus
		{
			get
			{
				return this._Guest_payingStatus;
			}
			set
			{
				if ((this._Guest_payingStatus != value))
				{
					this.OnGuest_payingStatusChanging(value);
					this.SendPropertyChanging();
					this._Guest_payingStatus = value;
					this.SendPropertyChanged("Guest_payingStatus");
					this.OnGuest_payingStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_confirmByReceptionist", DbType="VarChar(50)")]
		public string Guest_confirmByReceptionist
		{
			get
			{
				return this._Guest_confirmByReceptionist;
			}
			set
			{
				if ((this._Guest_confirmByReceptionist != value))
				{
					this.OnGuest_confirmByReceptionistChanging(value);
					this.SendPropertyChanging();
					this._Guest_confirmByReceptionist = value;
					this.SendPropertyChanged("Guest_confirmByReceptionist");
					this.OnGuest_confirmByReceptionistChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
